name: '*next*'
package:
  - '@kaname-png/plugin-statcord'
  - '@kaname-png/plugin-subcommands-advanced'
  - '@kaname-png/plugin-env'
  - '@kaname-png/plugin-api-jwt'
  - '@kaname-png/plugin-influxdb'
