import { createClassDecorator, createProxy } from '@sapphire/decorators';
import { Command, container, Piece } from '@sapphire/framework';

import { SlashCommandSubcommandBuilder } from '@discordjs/builders';

import { analizeSubcommandGroupParsed, analizeSubCommandParsed } from './functions';

export const RegisterSubCommand = (
	parentCommandName: string,
	slashSubcommand:
		| SlashCommandSubcommandBuilder
		| ((subcommandGroup: SlashCommandSubcommandBuilder, Container: typeof container) => SlashCommandSubcommandBuilder)
) => {
	return createClassDecorator((target: typeof Piece) =>
		createProxy(target, {
			construct: (ctor, [context, baseOptions]: [Piece.Context, Piece.Options]) => {
				const slashSubcommandParsed =
					typeof slashSubcommand === 'function' ? slashSubcommand(new SlashCommandSubcommandBuilder(), container) : slashSubcommand;

				const ctr = new ctor(context, {
					...baseOptions,
					name:
						container.client.options.subcommandsAdvanced?.nameCommandsAutogenerated === true
							? `${parentCommandName}/${slashSubcommandParsed.name}`
							: baseOptions.name
				}) as unknown as Command;

				return analizeSubCommandParsed(ctr, parentCommandName, slashSubcommandParsed);
			}
		})
	);
};

export const RegisterSubCommandGroup = (
	parentCommandName: string,
	groupName: string,
	slashSubcommand:
		| SlashCommandSubcommandBuilder
		| ((subcommandGroup: SlashCommandSubcommandBuilder, Container: typeof container) => SlashCommandSubcommandBuilder)
) => {
	return createClassDecorator((target: typeof Piece) =>
		createProxy(target, {
			construct: (ctor, [context, baseOptions]: [Piece.Context, Piece.Options]) => {
				const slashSubcommandParsed =
					typeof slashSubcommand === 'function' ? slashSubcommand(new SlashCommandSubcommandBuilder(), container) : slashSubcommand;

				const ctr = new ctor(context, {
					...baseOptions,
					name:
						container.client.options.subcommandsAdvanced?.nameCommandsAutogenerated === true
							? `${parentCommandName}/${groupName}/${slashSubcommandParsed.name}`
							: baseOptions.name
				}) as unknown as Command;

				return analizeSubcommandGroupParsed(ctr, parentCommandName, groupName, slashSubcommandParsed);
			}
		})
	);
};
