name: Check Botlists

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-botlists:
    name: Check Botlists
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Use Node.js v18
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 18
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Check botlists
        run: yarn workspace @kaname-png/plugin-bot-list check-bot-list
